/** All player-facing copy lives here (01 §4). */
export const S = {
  brand: '晨露田园',
  brandEn: 'Dewfield',
  intro: ['你接手了一座会过夜的玻璃露台。', '露台中央有一块七乘七的晨露田。', '市集的朋友们，正等着你的第一篮。'],
  start: '开始',
  newGame: '新游戏',
  continue: '继续',
  newGameConfirm: '会覆盖现在的露台，确定吗？',
  version: (b: string) => `版本 ${b}`,
  moves: '步数',
  dewdrop: '露珠',
  undo: '回退',
  pause: '暂停',
  resume: '继续',
  abandon: '放弃委托',
  abandonHint: '已交的货都算数，田照常留下。',
  won: '委托完成',
  lost: '步数用完了',
  abandoned: '先到这里',
  deliveredOf: (d: number, n: number) => `${d} / ${n}`,
  stillNeed: (n: number) => `还差 ${n} 个，交了的都算数。`,
  surplus: '余量卖出',
  unripe: '青作物',
  baseReward: '委托报酬',
  starBonus: '星级奖励',
  tutorialBonus: '剩余步数',
  total: '共得露珠',
  backToField: '回到露台',
  day: (n: number) => `第 ${n} 天`,
  morning: '晨',
  dusk: '暮',
  commission: '委托',
  startRun: '开始',
  close: '关闭',
  water: '浇垄',
  waterHint: '选一行浇水，整行作物当场长大一格',
  cancel: '取消',
  sleep: '入夜',
  sleepConfirm: '还有照料点没用，确定入夜吗？',
  notYet: '再看看',
  nightTitle: '夜深了',
  nightSub: '田里的作物，在月光下悄悄长大。',
  morningTitle: (n: number) => `第 ${n} 天 · 早安`,
  comeTomorrow: '市集收工了，明天再来',
  movesN: (n: number) => `${n} 步`,
  tapToSkip: '点击加速',
  fieldMemory: '收过的地方长出了新芽，这块田会记得你。',
  guideT1: '沿箭头，把发光的两格换一换',
  stars: '星级',
  terraceLevel: (n: number) => `露台 L${n}`,
  settings: '设置',
  bee: '放蜂',
  beeLocked: '购买蜂箱后解锁',
  beeLockedShort: '放蜂',
  beeHint: '选一株普通作物，放一窝蜂在它上面',
  waterGuide: '浇发光的那一行，它们会当场长大一格',
  shop: '商店',
  photo: '拍照',
  tomorrow: '按住看明早',
  owned: '已拥有',
  needLevel: (n: number) => `露台 L${n} 解锁`,
  volMaster: '主音量',
  volMusic: '音乐',
  volSfx: '音效',
  reducedMotion: '减弱动效',
  quality: '画质',
  qualityName: { auto: '自动', high: '高', low: '低' } as Record<'auto' | 'high' | 'low', string>,
  reset: '重置存档',
  resetConfirm: '再点一次确认重置（设置会保留）',
  exportCorrupt: (n: number) => `导出无法读取的旧档（${n}）`,
  done: '完成',
  gotIt: '知道了',
  watermark: (n: number) => `晨露田园 · 第 ${n} 天`,
  poseName: ['远景', '俯瞰', '侧光'] as const,
  shoot: '拍下',
  skip: '跳过',
  goWater: '先去浇水',
  lockedTitle: '游戏已在另一个标签页打开',
  lockedBody: '为了不弄乱你的露台，这一页先停下来了。',
  contextLostTitle: '画面需要重新加载',
  contextLostBody: '显卡暂时休息了一下。进度保存在最近的安全点，不会丢失。',
  reload: '重新加载',
  autoComplete: '够用了，谢谢！',
};

export const CLIENT_LINE = {
  amai: '阿麦 · 面包房',
  meiyi: '莓姨 · 果酱铺',
  laotao: '老陶 · 汤馆',
  xiaotang: '小糖 · 甜品站',
} as const;
